### PR TITLE
Test enhancement

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log
- Remove ```php-5.3``` support in ```composer.json```.
- Add the ```nightly``` test in Travis build.
- Change into the class-based PHPUnit name space.

### CODE REVIEW

**Comment by oscarotero** [comment]
Why you want to remove php5.3 support? This library is compatible with this version, it should not removed from composer.

**Comment by peter279k** [comment]
Some PHP syntax in source code don't support PHP ```5.3```.
If want to support ```php-5.3``` support, we have to change that syntax to the compatible syntax.

**Comment by oscarotero** [comment]
Drop php5.3 support means a new major version, something that I would't want to do for now.

**Comment by peter279k** [comment]
If possible, can I change that into the compatible syntax for ```php-5.3```?

**Comment by peter279k** [comment]
@oscarotero, now I add the ```5.3.0``` back in ```composer.json```.
And I hope it can release the latest version to drop the ```php-5.3``` support :+1: .

**Comment by oscarotero** [comment]
Thanks!

**Pull request merged**
